### ISSUE TITLE
error: command '/usr/bin/gcc' failed with exit code 1&make: *** [Makefile:7: all] Error 1

### ISSUE THREAD

**Issue by Tankaishen** [MPI-IS/mesh#106]
error: command '/usr/bin/gcc' failed with exit code 1
  error: subprocess-exited-with-error
  
  × Building wheel for psbody-mesh (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /root/anaconda3/envs/pytorch/bin/python3.9 /root/anaconda3/envs/pytorch/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py build_wheel /tmp/tmpn2iglis_
  cwd: /data/mesh-fix-MSVC_compilation
  Building wheel for psbody-mesh (pyproject.toml) ... error
  ERROR: Failed building wheel for psbody-mesh
Failed to build psbody-mesh
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (psbody-mesh)
make: *** [Makefile:7: all] Error 1

I have installed gcc and g++ and replace the install-options with config-settings in Makefile:7, But I still met this error. How to solve it?

**Comment by yjhong89** [comment]
Same error with me

**Comment by Tankaishen** [comment]
I created a new environment and ran “make all”. It success! Why? I think if there is some package that is conflict with the installation of psbody.

**Comment by yjhong89** [comment]
Without BOOST_INCLUDE_DIRS ??

**Comment by Tankaishen** [comment]
> Without BOOST_INCLUDE_DIRS ??

Use the cd command to the folder downloaded from this repository, which contains the "Makefile". If the Working directory is this folder, there is no need to include the string "BOOST_INCLUDE_DIRS"

**Comment by Pamimi** [comment]
> I created a new environment and ran “make all”. It success! Why? I think if there is some package that is conflict with the installation of psbody.

It seems that the version of numpy might have caused the compilation to fail. After downgrading my numpy version from 2.0.1 to 1.26,  the compilation was successful.

**Comment by DAnonyvinciT** [comment]
I found it worked in python 3.9 but failed in python3.10

**Comment by mcsenne** [comment]
> > I created a new environment and ran “make all”. It success! Why? I think if there is some package that is conflict with the installation of psbody.
> 
> It seems that the version of numpy might have caused the compilation to fail. After downgrading my numpy version from 2.0.1 to 1.26, the compilation was successful.

This and removing numpy from the requirements.txt worked for me, as it reinstalled a newer version every time I ran the command.

I use python 3.10 had a similar error by trying to run "BOOST_INCLUDE_DIRS=/usr/include/boost make all" (inside 'mesh' folder).

**Comment by sambaPython24** [comment]
Even after the numpy version 1.26, I still have the error 
```
  mesh/src/aabb_normals.cpp:159:71: error: cannot convert ‘PyObject*’ {aka ‘_object*’} to ‘const PyArrayObject*’ {aka ‘const tagPyArrayObject_fields*’}
    159 |         closest_point=reinterpret_cast<array<double,3>*>(PyArray_DATA(result2));
        |                                                                       ^~~~~~~
        |                                                                       |
        |                                                                       PyObject* {aka _object*}
  /tmp/pip-build-env-0iz6e06a/normal/lib/python3.9/site-packages/numpy/_core/include/numpy/ndarraytypes.h:1508:35: note:   initializing argument 1 of ‘void* PyArray_DATA(const PyArrayObject*)’
   1508 | PyArray_DATA(const PyArrayObject *arr)
        |              ~~~~~~~~~~~~~~~~~~~~~^~~
  error: command '/usr/bin/g++' failed with exit code 1
  error: subprocess-exited-with-error
```

Anybody else with the same error or an idea?

**Comment by liza-li** [comment]
> Even after the numpy version 1.26, I still have the error
> 
> ```
>   mesh/src/aabb_normals.cpp:159:71: error: cannot convert ‘PyObject*’ {aka ‘_object*’} to ‘const PyArrayObject*’ {aka ‘const tagPyArrayObject_fields*’}
>     159 |         closest_point=reinterpret_cast<array<double,3>*>(PyArray_DATA(result2));
>         |                                                                       ^~~~~~~
>         |                                                                       |
>         |                                                                       PyObject* {aka _object*}
>   /tmp/pip-build-env-0iz6e06a/normal/lib/python3.9/site-packages/numpy/_core/include/numpy/ndarraytypes.h:1508:35: note:   initializing argument 1 of ‘void* PyArray_DATA(const PyArrayObject*)’
>    1508 | PyArray_DATA(const PyArrayObject *arr)
>         |              ~~~~~~~~~~~~~~~~~~~~~^~~
>   error: command '/usr/bin/g++' failed with exit code 1
>   error: subprocess-exited-with-error
> ```
> 
> Anybody else with the same error or an idea?

You can try this one: https://github.com/MPI-IS/mesh/issues/91#issue-1742830150
